# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07925f6755224e66b7f692151b31888439c87df5cce0ec98c1d7a7efdd43fef3d7cae092b9e9a027dea2aaf63b2ffb2d036eff0bc055e18c462e0b26942ae6b8

test:
  secret_key_base: 5a82ec27339a0de180c25a15c224a04d8757b6e0db55ab560413721b1cde1b8bfff83ffd6fc45917321010f4a2cf3bb352b8ffc77eb438363ab38a6a54437262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
