# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96dbe7bf94f2f370a6637ac1f200f384badda071313db3fcb487e8dcfd212265620daac819fc4c8dadb0454f9e1c685762e264e853eb435efbe95e251c5dc566

test:
  secret_key_base: 611f901c681ccd710c20f56bf4e1768259ba1bd5089ed422024ce47563abbf0118468ac3e79832dcd9c7371d310f0d00827e34b5f859d060a76b76caa346d63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
